version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.23.2
    restart: always
    ports:
    - "4460:4460"
    environment:
      PRISMA_CONFIG: |
        port: 4460
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            user: prisma
            password: ${DB_PASSWORD}
            rawAccess: true
            port: 5432
            migrations: true
  postgres:
    image: postgres:11.1
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
